# Generated by Django 4.2.15 on 2024-08-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        help_text="Укажите номер телефона контакта",
                        max_length=100,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите адрес электронной почты контакта",
                        max_length=254,
                        verbose_name="Адрес электронной почты",
                    ),
                ),
                (
                    "INN",
                    models.CharField(
                        help_text="Укажите ИНН контакта",
                        max_length=12,
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "OGRN",
                    models.CharField(
                        help_text="Укажите ОГРН контакта",
                        max_length=15,
                        verbose_name="ОГРН",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["contact"],
            },
        ),
    ]
