# Generated by Django 4.2.15 on 2024-08-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_rename_inn_contact_inn_rename_ogrn_contact_ogrn"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите заголовок",
                        max_length=100,
                        verbose_name="Заголовок",
                    ),
                ),
            ],
        ),
    ]
