# Generated by Django 4.2.15 on 2024-08-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Укажите содержимое",
                null=True,
                verbose_name="Содержимое",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Введите дату",
                null=True,
                verbose_name="Дата создания записи",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/image", verbose_name="Фото"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(
                default=True, help_text="Выберите публикацию", verbose_name="Публикация"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
